const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const vertex = require('./modules/vertex');
const ffmpeg = require('./modules/ffmpeg');
const render = require('./modules/render');
let f5TTS = null;

require('./modules/f5-tts').initF5TTS({
  baseUrl: 'http://localhost:7860',
  referenceAudioPath: path.join(__dirname, 'afi-voice-trim.wav'),
  referenceText: fs.readFileSync(path.join(__dirname, 'afi-voice-trim.txt'), 'utf8'),
  randomizeSeed: false,
  removeSilences: false,
  seed: 52531120,
  crossFadeDuration: 0.02,
  pitchShift: 38,
  speedChange: 1.0,
}).then((_) => {
  console.log('F5 TTS initialized');
  f5TTS = _;
});

function padNr(nr) {
  return nr.toString().padStart(2, '0');
}

function formatYouTubeTimestamp(seconds) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);

  if (h > 0) {
    return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  } else {
    return `${m}:${String(s).padStart(2, '0')}`;
  }
}


function listProjects() {
  // Get the absolute path to the "projects" directory
  const projectsPath = path.join(__dirname, 'projects');

  // Check if it exists
  if (!fs.existsSync(projectsPath)) {
    console.log('No projects directory found.');
    return [];
  }

  // Read all items inside the projects folder
  const items = fs.readdirSync(projectsPath);

  // Filter only directories
  const folders = items.filter(item => {
    const itemPath = path.join(projectsPath, item);
    return fs.statSync(itemPath).isDirectory();
  });

  return folders;
}

async function generateAssets(project, engineUrl) {
  const projectPath = path.join(__dirname, 'projects', project);
  const projectDefinition = path.join(projectPath, 'proj.yml');

  // Check if it exists
  if (!fs.existsSync(projectPath)) {
    console.log('No projects directory found.');
    return null;
  }

  // Check if definition exists
  if (!fs.existsSync(projectDefinition)) {
    console.log('No project projectDefinition found.');
    return null;
  }

  const fileContents = fs.readFileSync(projectDefinition, 'utf8');
  const data = yaml.load(fileContents);

  let slideIndex = 0;

  for (const slide of data.slides) {
    const title = slide.title;
    const renderType = slide.renderType;

    let fragmentIndex = 0;
    let lastFragmentAppendData = {
      text: '',
      ulist: [],
      olist: [],
    };

    for (const fragment of slide.fragments) {
      const speech = fragment.textToSpeech.trim();

      // Render image with assets
      // # TODO showcase generated by AI
      const renderFile = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-render.png`);
      const data = {
          title: fragment.noTitle ? '' : title,
          subtitle: fragment.subtitle,
          text: fragment.textAppend ? (lastFragmentAppendData.text || '') + ' ' + fragment.textAppend : fragment.text,
          ulist: fragment.ulistAppend ? [...lastFragmentAppendData.ulist || [], ...fragment.ulistAppend] : fragment.ulist,
          olist: fragment.olistAppend ? [...lastFragmentAppendData.olist || [], ...fragment.olistAppend] : fragment.olist,
          showcaseImage: fragment.showcaseImage ? render.imageToHtmlBase64(path.join(projectPath, fragment.showcaseImage)) : null,
        };


      if (!fs.existsSync(renderFile)) {
        
        let binaryRender;

        switch (renderType) {
          case 'intro':
            binaryRender = await render.renderIntro(engineUrl, data);
            break;
          case 'outro':
            binaryRender = await render.renderOutro(engineUrl, data);
            break;
          default:
            binaryRender = await render.renderSlide(engineUrl, data);
            break;
        }

        await fs.promises.writeFile(renderFile, binaryRender);
      }

      // Render text to speech
      // const speechFile = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-speech.mp3`);
      const speechFile = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-speech.wav`);
      if (!fs.existsSync(speechFile)) {
        await f5TTS.textToSpeech(speech, speechFile);
        // const audioBase64Content = await vertex.textToSpeech(speech);
        // await fs.promises.writeFile(speechFile, Buffer.from(audioBase64Content, 'base64'));
      }

      fragmentIndex++;

      lastFragmentAppendData.text = data.text;
      lastFragmentAppendData.olist = data.olist;
      lastFragmentAppendData.ulist = data.ulist;
    }

    slideIndex++;
  }

  return data;
}

async function renderVideo(project) {
  const projectPath = path.join(__dirname, 'projects', project);
  const projectDefinition = path.join(projectPath, 'proj.yml');

  // Check if it exists
  if (!fs.existsSync(projectPath)) {
    console.log('No projects directory found.');
    return null;
  }

  // Check if definition exists
  if (!fs.existsSync(projectDefinition)) {
    console.log('No project projectDefinition found.');
    return null;
  }

  const fileContents = fs.readFileSync(projectDefinition, 'utf8');
  const data = yaml.load(fileContents);

  let slideIndex = 0;

  const videoFragments = [];

  for (const slide of data.slides) {
    const title = slide.title;
    const renderType = slide.renderType;

    let fragmentIndex = 0;

    

    for (const fragment of slide.fragments) {
      const renderFile = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-render.png`);
      const speechFile = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-speech.wav`);
      // const speechFile = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-speech.mp3`);

      if (!fs.existsSync(renderFile)) {
        throw {
          err: `Render file file for slide ${slideIndex}, fragment ${fragmentIndex} not found!`
        }
      }

      if (!fs.existsSync(speechFile)) {
        throw {
          err: `Speech file for slide ${slideIndex}, fragment ${fragmentIndex} not found!`
        }
      }

      const fragmentVideoPath = path.join(projectPath, `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-video.mp4`);

      await ffmpeg.generateMp4FromPngAndMp3(renderFile, speechFile, fragmentVideoPath);

      videoFragments.push(fragmentVideoPath);

      fragmentIndex++;
    }

    slideIndex++;
  }

  const finalVideoPath = path.join(projectPath, `project-${project}.mp4`);

  await ffmpeg.concatMp4s(projectPath, videoFragments, finalVideoPath);

  return finalVideoPath;
}

async function generateChapters(project) {
  const projectPath = path.join(__dirname, 'projects', project);
  const projectDefinition = path.join(projectPath, 'proj.yml');

  // Check if it exists
  if (!fs.existsSync(projectPath)) {
    console.log('No projects directory found.');
    return null;
  }

  // Check if definition exists
  if (!fs.existsSync(projectDefinition)) {
    console.log('No project projectDefinition found.');
    return null;
  }

  const fileContents = fs.readFileSync(projectDefinition, 'utf8');
  const data = yaml.load(fileContents);

  let slideIndex = 0;

  const chapters = [];
  let durationHead = 0;

  for (const slide of data.slides) {
    let fragmentIndex = 0;
    const chapterName = slide.title;
    let chapterDuration = 0;

    for (const fragment of slide.fragments) {
      const mp4Name = `slide${padNr(slideIndex)}_fragment${padNr(fragmentIndex)}-video.mp4`
      const mp4File = path.join(projectPath, mp4Name);

      if (!fs.existsSync(mp4File)) {
        throw {
          err: `Video file for slide ${slideIndex}, fragment ${fragmentIndex} not found!`
        }
      }

      const duration = await ffmpeg.getAudioDuration(mp4File);
      
      chapterDuration += duration;

      fragmentIndex++;
    }

    const youtubeTs = formatYouTubeTimestamp(durationHead);
    console.log(`Duration of chapter ${slideIndex} (${chapterName}) is ${chapterDuration} seconds, HEAD at: ${youtubeTs}`);

    chapters.push(`${youtubeTs} ${chapterName}`);

    slideIndex++;
    durationHead += chapterDuration;
  }

  const chaptersFile = path.join(projectPath, `project-${project}-chapters.txt`);
  const chaptersStr = chapters.join('\n');

  await fs.promises.writeFile(chaptersFile, Buffer.from(chaptersStr));

  return chaptersStr;
}

module.exports = {
  listProjects,
  generateAssets,
  renderVideo,
  generateChapters,
};